# base image

FROM node:25-alpine3.22

# working file
WORKDIR /home/app

# copying file
COPY package*.json .
COPY tsconfig.json .

RUN npm install

COPY src/ src/

RUN npm run build

CMD ["npm", "run", "dev"]